# Generated by Django 4.1.3 on 2022-12-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('selling_price', models.FloatField(null=True)),
                ('discounting_price', models.FloatField(null=True)),
                ('description', models.TextField()),
                ('composition', models.CharField(default='', max_length=200)),
                ('prodapp', models.CharField(default='', max_length=200)),
                ('category', models.CharField(choices=[('MK', 'Milk'), ('TM', 'Tomato'), ('MS', 'Milkshake'), ('EG', 'Egg'), ('BN', 'Banana'), ('IC', 'Ice-Cream')], max_length=2)),
                ('product_image', models.ImageField(upload_to='app/product')),
            ],
        ),
    ]
